### ISSUE TITLE
Bug: ImportError: cannot import name 'url_encode'

### ISSUE THREAD

**Issue by Kaoloth** [scoringengine/scoringengine#672] opened 2020-02-09 17:09 UTC
Following the straightforward instructions for getting the docker container up and running:
```
git clone https://github.com/scoringengine/scoringengine.git
docker-compose build
docker-compose up
```

leads to the following error in the web module:

```
web_1        | bootstrap container is finished...starting container
web_1        | Traceback (most recent call last):
web_1        |   File "/app/bin/web", line 5, in <module>
web_1        |     from scoring_engine.web import app as application
web_1        |   File "/app/scoring_engine/web/__init__.py", line 18, in <module>
web_1        |     from scoring_engine.web.views import welcome, scoreboard, overview, services, admin, auth, profile, api, about
web_1        |   File "/app/scoring_engine/web/views/auth.py", line 4, in <module>
web_1        |     from flask_wtf import FlaskForm
web_1        |   File "/venv/lib/python3.6/site-packages/flask_wtf/__init__.py", line 17, in <module>
web_1        |     from .recaptcha import *
web_1        |   File "/venv/lib/python3.6/site-packages/flask_wtf/recaptcha/__init__.py", line 2, in <module>
web_1        |     from .fields import *
web_1        |   File "/venv/lib/python3.6/site-packages/flask_wtf/recaptcha/fields.py", line 3, in <module>
web_1        |     from . import widgets
web_1        |   File "/venv/lib/python3.6/site-packages/flask_wtf/recaptcha/widgets.py", line 5, in <module>
web_1        |     from werkzeug import url_encode
web_1        | ImportError: cannot import name 'url_encode'
```

This appears to be caused by changes in later versions of a Flask dependency, werkzeug, as I found in [this stackoverflow question.](https://stackoverflow.com/questions/60104484/cannot-run-apache-airflow-after-fresh-install-python-import-error).

I fixed it by specifying the exact version of werkzeug in the setup.py file, pinning it to 0.16.0. A later version may still work.

More specifically, I changed the install_requires array from
```
    'install_requires': [
        'bcrypt==3.1.3',
        'billiard==3.5.0.4',
        'celery==4.2.2',
        'configparser==3.5.0',
        'Flask==1.0.2',
        'Flask-Caching==1.4.0',
        'Flask-Login==0.4.0',
        'Flask-SQLAlchemy==2.2',
        'Flask-WTF==0.14.2',
        'mysqlclient==1.3.12',
        'pynsive==0.2.7',
        'PyYAML==4.2b4',
        'redis==3.2',
        'shellescape==3.4.1'
    ]
```
to
```
    'install_requires': [
        'bcrypt==3.1.3',
        'billiard==3.5.0.4',
        'celery==4.2.2',
        'configparser==3.5.0',
        'Flask==1.0.2',
        'Flask-Caching==1.4.0',
        'Flask-Login==0.4.0',
        'Flask-SQLAlchemy==2.2',
        'Flask-WTF==0.14.2',
        'mysqlclient==1.3.12',
        'pynsive==0.2.7',
        'PyYAML==4.2b4',
        'redis==3.2',
        'shellescape==3.4.1',
        'werkzeug==0.16.0'
    ]
```
After the fix, I re-ran 
```
docker-compose build
docker-compose up
```
and the scoreboard functioned as expected.

**Comment by RustyBower** [comment] 2020-02-09 17:18
Closing this as a dupe of #670, and this should be fixed in #671

**Closed as completed by RustyBower** 2020-02-09 17:18 UTC
